import Decimal from "decimal.js";
import type { Holding, Portfolio, Snapshot, LedgerEvent } from "./types";
const at = "2026-09-18T06:30:00.000Z";
const rows = [
  [
    "cash-cny",
    "人民币",
    "CNY",
    "cash",
    "法币",
    "CNY",
    "元",
    "185000",
    "1",
    "1",
    "185000",
    "招商银行",
    "bank",
  ],
  [
    "stock-aapl",
    "苹果 Apple",
    "AAPL",
    "stock",
    "NASDAQ",
    "USD",
    "股",
    "120",
    "228.87",
    "7.12",
    "195546.528",
    "海外证券",
    "broker",
  ],
  [
    "stock-700",
    "腾讯控股",
    "00700",
    "stock",
    "HKEX",
    "HKD",
    "股",
    "600",
    "412.8",
    "0.91",
    "225388.8",
    "海外证券",
    "broker",
  ],
  [
    "fund-110022",
    "易方达消费行业股票",
    "110022",
    "fund",
    "中国公募",
    "CNY",
    "份",
    "50000",
    "3.1876",
    "1",
    "159380",
    "基金账户",
    "fund",
  ],
  [
    "gold-au9999",
    "Au99.99 足金金条",
    "Au99.99",
    "gold",
    "实物黄金",
    "CNY",
    "克",
    "100",
    "596",
    "1",
    "59594.04",
    "招商银行",
    "bank",
  ],
  [
    "crypto-bitcoin",
    "比特币",
    "BTC",
    "crypto",
    "全球",
    "USD",
    "枚",
    "0.32",
    "63280",
    "7.12",
    "144176.512",
    "数字钱包",
    "wallet",
  ],
  [
    "cash-usd",
    "美元",
    "USD",
    "cash",
    "法币",
    "USD",
    "美元",
    "15000",
    "1",
    "7.12",
    "106800",
    "海外证券",
    "broker",
  ],
] as const;
const items: Holding[] = rows.map(
  ([
    id,
    name,
    symbol,
    type,
    market,
    currency,
    unit,
    quantity,
    price,
    fx,
    value,
    accountName,
    accountId,
  ]) => ({
    id,
    holdingId: `${accountId}~${id}`,
    name,
    symbol,
    type,
    market,
    currency,
    unit,
    quantity,
    originalValue: new Decimal(value).div(fx).toFixed(),
    price,
    fx,
    value,
    accountName,
    accountId,
    ownerId: null,
    providerId: null,
    purity: type === "gold" ? "0.9999" : "1",
    quoteBasis: "unit",
    source: "演示报价",
    fxSource: "演示汇率",
    priceAsOf: at,
    fxAsOf: at,
    status: type === "gold" ? "manual" : "current",
  }),
);
const total = "1075885.88";
const history: Snapshot[] = Array.from({ length: 30 }, (_, i) => {
  const value =
    990000 + i * 2650 + Math.sin(i * 0.8) * 11500 + Math.cos(i * 1.9) * 2400;
  return {
    id: `demo-${i}`,
    asOf: new Date(Date.UTC(2026, 7, 20 + i)).toISOString(),
    total: i === 29 ? total : value.toFixed(2),
    netFlow: "20000",
    pnl: (value - 990000).toFixed(2),
    complete: true,
    version: 1,
    items: [],
  };
});
const transactions: LedgerEvent[] = [
  {
    id: "demo-1",
    type: "deposit",
    occurredAt: at,
    note: "九月储蓄 · 工资转入",
    externalCny: "20000",
    legs: [{ accountId: "bank", instrumentId: "cash-cny", quantity: "20000" }],
  },
  {
    id: "demo-2",
    type: "buy",
    occurredAt: "2026-09-17T10:00:00.000Z",
    note: "长期定投",
    externalCny: "0",
    legs: [{ accountId: "broker", instrumentId: "stock-aapl", quantity: "10" }],
  },
  {
    id: "demo-3",
    type: "dividend",
    occurredAt: "2026-09-16T08:00:00.000Z",
    note: "季度现金分红",
    externalCny: "0",
    legs: [{ accountId: "broker", instrumentId: "cash-usd", quantity: "68.4" }],
  },
].map((e) => ({
  ...e,
  userId: "demo",
  createdAt: e.occurredAt,
  baselineAdjustment: "0",
  status: "active",
  idempotencyKey: e.id,
  payload: "{}",
})) as LedgerEvent[];
export const demoPortfolio: Portfolio = {
  name: "Alex",
  email: "demo@example.com",
  emailVerified: true,
  demo: true,
  holdings: items,
  accounts: [
    ...new Map(
      items.map((h) => [
        h.accountId,
        {
          id: h.accountId,
          userId: "demo",
          name: h.accountName,
          type: "资产账户",
          archived: 0,
        },
      ]),
    ).values(),
  ],
  transactions,
  total,
  complete: true,
  missingCount: 0,
  staleCount: 0,
  netFlow: "20000",
  pnl: "85885.88",
  baseline: "970000",
  baselineAt: history[0].asOf,
  change: "28642.56",
  periodFlow: "20000",
  periodPnl: "8642.56",
  history,
  asOf: at,
  initialized: true,
};
