import type { Instrument } from "@/lib/types";
export const catalog: Instrument[] = [
  ["cash-cny", "人民币", "CNY", "cash", "法币", "CNY", "元", null],
  ["cash-usd", "美元", "USD", "cash", "法币", "USD", "美元", null],
  ["cash-hkd", "港元", "HKD", "cash", "法币", "HKD", "港元", null],
  ["stock-aapl", "苹果 Apple", "AAPL", "stock", "NASDAQ", "USD", "股", "AAPL"],
  [
    "stock-baba",
    "阿里巴巴 Alibaba（美股）",
    "BABA",
    "stock",
    "NYSE",
    "USD",
    "股",
    "BABA",
  ],
  [
    "stock-msft",
    "微软 Microsoft",
    "MSFT",
    "stock",
    "NASDAQ",
    "USD",
    "股",
    "MSFT",
  ],
  [
    "stock-nvda",
    "英伟达 NVIDIA",
    "NVDA",
    "stock",
    "NASDAQ",
    "USD",
    "股",
    "NVDA",
  ],
  [
    "stock-vti",
    "Vanguard 全美股票 ETF",
    "VTI",
    "stock",
    "NYSE",
    "USD",
    "份",
    "VTI",
  ],
  ["stock-700", "腾讯控股", "00700", "stock", "HKEX", "HKD", "股", "0700:HKEX"],
  [
    "stock-600519",
    "贵州茅台",
    "600519",
    "stock",
    "SSE",
    "CNY",
    "股",
    "600519:SSE",
  ],
  [
    "fund-110022",
    "易方达消费行业股票",
    "110022",
    "fund",
    "中国公募",
    "CNY",
    "份",
    "110022.OF",
  ],
  [
    "gold-au9999",
    "Au99.99 足金金条",
    "Au99.99",
    "gold",
    "实物黄金",
    "CNY",
    "克",
    null,
  ],
  ["crypto-bitcoin", "比特币", "BTC", "crypto", "全球", "USD", "枚", "bitcoin"],
  [
    "crypto-ethereum",
    "以太坊",
    "ETH",
    "crypto",
    "全球",
    "USD",
    "枚",
    "ethereum",
  ],
  ["crypto-tether", "Tether", "USDT", "crypto", "全球", "USD", "枚", "tether"],
  [
    "crypto-raydium",
    "Raydium",
    "RAY",
    "crypto",
    "全球",
    "USD",
    "枚",
    "raydium",
  ],
].map(([id, name, symbol, type, market, currency, unit, providerId]) => ({
  id,
  name,
  symbol,
  type,
  market,
  currency,
  unit,
  providerId,
  ownerId: null,
  purity: type === "gold" ? "0.9999" : "1",
  quoteBasis: "unit",
})) as Instrument[];
